expt_dir: experiments
num_colors: 6
num_out_channels: 7
expt_name: mean_flow_mnist
trainer_args:
  max_epochs: 100
  accelerator: "gpu"
  devices: [0,1]
  limit_train_batches: 3200
  limit_val_batches: 1
  check_val_every_n_epoch: 1
  log_every_n_steps: 5
  precision: 32
  strategy: "deepspeed_stage_2"
diffusion_trainer:
  target: pl_trainer.mean_flow_trainer.MeanFlowTrainer
  params:
    accumulate_grad_batches: 1 #2
    loss_weights: 
      focal_xentropy: 1.0
    optim_args: 
      lr: 5e-5
      weight_decay: 1e-5
    use_8bit_adam: False
    gradient_checkpointing: True
    use_ema: True
    ema_decay: 0.99
    ema_start: 50000
    cond_drop_rate: 0.1
    guidance_scale: 4.0
pipe:
  target: pipelines.mean_flow_pipeline.MeanFlowPipeline
  params: {}
denoiser: 
  target: models.mean_flow_model.DualTimestepDiTTransformer2DModel
  params:
    in_channels: 3
    out_channels: 3
    num_layers: 12
    num_attention_heads: 8
    attention_head_dim: 64
data:
  batch_size: 8 #16
  val_batch_size: 8
  train_shuffle: true
  val_shuffle: true
  collate_fn: 
    target: diffusion_datasets.dataset_utils.image_edge_unet_collate_fn
  train:
    target: diffusion_datasets.dataset_utils.JointDataset
    params:
      mode: "train"
      sampling_rates:
        - 1.
      subdatasets:
        - target: diffusion_datasets.edge_datasets.LAION_synthetic.LAIONSyntheticQuantizedLabeledDataset
          params: 
            root_dir: /home/devdata/laion/edge_detection
            image_shape: 
              - ${image_size}
              - ${image_size}
            mode: train
            num_colors: ${num_colors}
  val:
    target: diffusion_datasets.dataset_utils.ConcatDataset
    params:
      mode: "val"
      subdatasets:
        - target: diffusion_datasets.edge_datasets.LAION_synthetic.LAIONSyntheticQuantizedLabeledDataset
          params: 
            root_dir: /home/devdata/laion/edge_detection
            image_shape: 
              - ${image_size}
              - ${image_size}
            num_colors: ${num_colors}
            mode: test
            max_samples: 100
callbacks:
  - target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: "${expt_dir}/${expt_name}"
      filename: "{epoch:04d}"
      monitor: epoch
      mode: max
      save_top_k: 2
      save_last: true
  - target: callbacks.training_visualizer.DiffusionTrainingLogger
    params:
      max_num_images: 8
    require_wandb: true
